---
title: "R_Cheat_Sheet_CMAR"
author: "Nicole Torrie"
date: "14/05/2020"
output: html_document
---
This document is for storage of packages, functions, and R Code useful for CMAR operations


Some Mapping Packages
```{r}
install.packages("ggplot2")
install.packages("ggrepel")
install.packages("ggspatial")
install.packages("libwgeom")
install.packages("sf")
install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
install.packages("rgeos")
install.packages("oce")
install.packages("marmap")
install.packages("ggsn")
install.packages("grid")

library(ggplot2) #graphical plotting - based on data frames
library(maps) #basic mapping packages with useful spatial data (i.e., bounding polygons, land, coastlines, etc)
library(mapdata) #even more mapping data
library(marmap) #package to get bathymetric data
library(dplyr) #data manipulation package
library(tidyr) #package with extended data manipulation in addition to dplyr
library(ggsn) #package that permits scale bars in ggplot
library(png) #for loading images
```

Color Pallet
```{r}

```

Read from Excel
```{r}

read.excel <- function(header=TRUE,...) {
  read.table("clipboard",sep="\t",header=header,...)
}

#dat<-read.excel()
#dat
```


Merging Data
```{r}
proteome.merge <- merge(database,raw.proteome,by.x="seq_name",by.y="Accession",all.x=F)
write.table(proteome.merge, file = "Whole Proteome Merge.csv", sep =",", row.names = FALSE, quote = FALSE,qmethod = "double") 
```

View a plot in full screen
```{r}
#ctrl+shift+6
```


```{r}
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval:  the percent range of the confidence interval (default is 95%)
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
  # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}
```


